# -*- coding: utf-8 -*-
"""FinalProjectClassificationModel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kVikcrqDv0a8xTX-_muoTWdJx9gz-Haw
"""

import numpy as np
import pandas as pd
from google.colab import drive
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import RobustScaler, OneHotEncoder

drive.mount("/content/drive")

#Setup the Data
data = pd.read_csv('master_cleaned.csv',header=0,index_col=None)

#Setup Data
x_data = data.drop(columns=['Label'])
x_data = x_data.drop(columns=['Country'])
y_data = data[['Label']]

#Turn text labels into encoded categories
from sklearn.preprocessing import LabelBinarizer
encoder = LabelBinarizer()
y_data = encoder.fit_transform(y_data)

#Scale the data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_data)
x_data = scaler.transform(x_data)

#Setup Testing Sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.3, shuffle=False)

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

#Fit the model to the training data
regr = KNeighborsClassifier(n_neighbors=3)
regr.fit(x_train,y_train)

#Predict labels for the testing data
preds = regr.predict(x_test)

#Reshape the data into a readable array for accuracy check
preds = preds.reshape(-1,1)

#Calculate accuracy
print("Accuracy is: ")
print(accuracy_score(y_test, preds))